#服务器配置
server:
    port: 9000
    context-path: /manage
#数据库
spring:
   datasource:
       url: jdbc:mysql://121.196.211.33:3306/metchange_user_center
       username: ytkj
       password: 123456
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver
       filters: stat
       maxActive: 20
       initialSize: 1
       maxWait: 60000
       minIdle: 1
       timeBetweenEvictionRunsMillis: 60000
       minEvictableIdleTimeMillis: 300000
       validationQuery: select 'x'
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       poolPreparedStatements: true
       maxOpenPreparedStatements: 20
   redis:
       database: 0
     # Redis服务器地址
       host: 192.168.41.78
     # Redis服务器连接端口
       port: 6379
     # Redis服务器连接密码（默认为空）
       password:
     # 连接池最大连接数（使用负值表示没有限制）
       pool.max-active: 8
     # 连接池最大阻塞等待时间（使用负值表示没有限制）
       pool.max-wait: -1
     # 连接池中的最大空闲连接
       pool.max-idle: 8
     # 连接池中的最小空闲连接
       pool.min-idle: 0
     # 连接超时时间（毫秒）
       max-active: 500 # 连接池最大连接数（使用负值表示没有限制）
       timeout: 100000 # 连接超时时间（毫秒）

redis.sessionTimeout: 30 #session超时时间（分钟）
#分页插件
pagehelper:
    helperDialect: mysql
    returnPageInfo: check
    supportMethodsArguments: true
    reasonable: true
    params: count=countSql
#mybatis映射
mybatis:
  mapper-locations: classpath:mapping/*/*.xml
  type-aliases-package: com.lcl.*.entity.po
#JWT校验策略
jwt:
  secret: secret
  expiration: 30